### ISSUE TITLE
CheckPermissions return empty for current subscriptions

### ISSUE THREAD

**Issue by jorgevalbuena56** [qonversion/android-sdk#101]
Hello,

I am trying to integrate the SDK in Android using the latest version. I have my checkPermisssions method to give me information about the susbcriptions of a user. For a user that doesn't have subscriptions the hashMap is empty which is good, then I am calling purchase to susbcribe and the subscription is completed successfully. Next Time I call the checkPermisssion method, the hashMap is not empty which is good. The problem comes when the subscription expire.

For that case the checkPermisssions hashMap is empty and I prompt the user to buy a subscription but this one fails saying: You have already subscribe to this item. What's the reliable way to know if a user has a subscription to my product, either active or cancel?

I am testing in this with the "view testing data on" and only using Products, not offerings.

i can post my code later, but I think my problem is the confusing behaviour of the checkPermissions method.

**Comment by Maria-Bordunova** [comment]
Hi, @jorgevalbuena56 !
Thank you for contacting us. We will investigate the problem and return with the answer in the near future.

**Comment by Maria-Bordunova** [comment]
Hi again, @jorgevalbuena56 

Do you test the `purchase` and the `checkPermissions` methods on the same device ?
How do you know that subscription is expired? Do you use the Customers panel on [Qonversion Dashboard](https://dash.qonversion.io/customers/index) ?

It is really weird that you get an empty permissions map after subs expiration because Qonversion returns permission for expired subscription with **inactive status**. So you should check status for permission via `isActive()` method for QPermission. Here is an example how you can check it:


```
Qonversion.checkPermissions(object: QonversionPermissionsCallback {
            override fun onSuccess(permissions: Map<String, QPermission>) {
                val premiumPermission = permissions["premium"]
                if (premiumPermission != null && premiumPermission.isActive()) {
                    // handle active permission here
                }
            ...
})
```

More details about Permissions you can find [here](https://documentation.qonversion.io/docs/making-purchases#3-check-user-permissions ).

**Comment by Maria-Bordunova** [comment]
Moreover, if you are getting the following message `You have already subscribe to this item`, it means that you really have subscription for required item.

**Comment by jorgevalbuena56** [comment]
Hi @Maria-Bordunova 

Thanks for your reply. I took another closer look at my code and I am follow the steps you mentioned. I am using only one phone for all testing with Android 11.

I realised that the problem seems to be the purchase method. It hits the success callback but the permissions there are empty after the purchase is made. For some reason is not registering that the purchase was successfully done. 

When I go to the subscriptions page in the google play library is active.

Here are some screenshoots of my flow

<img width="945" alt="Screen Shot 2021-01-19 at 6 27 11 am" src="https://user-images.githubusercontent.com/7516423/104960632-58312080-5a20-11eb-9a52-f50bffc9212f.png">

<img width="301" alt="Screen Shot 2021-01-19 at 6 33 26 am" src="https://user-images.githubusercontent.com/7516423/104960654-61ba8880-5a20-11eb-8b9f-8f8817982977.png">

**Comment by jorgevalbuena56** [comment]
Another weird issue is that I am not seeing anything in the Qonversion Dashboard regarding that subscription

<img width="1185" alt="Screen Shot 2021-01-19 at 6 37 13 am" src="https://user-images.githubusercontent.com/7516423/104960868-e60d0b80-5a20-11eb-9837-57d45b1ff4ec.png">

**Comment by Maria-Bordunova** [comment]
@jorgevalbuena56 Thank you for the information. We are working on your case and will let you know as soon as possible.

**Comment by Maria-Bordunova** [comment]
@jorgevalbuena56 Thanks for your patience and waiting. 
We tried to reproduce the scenario. It seems to us that something is wrong with the **Google Play Service Account Key** you provided to Qonversion. Qonversion was not able to verify the purchase and hence create any permission for the purchase. 
Please make sure that you:

-  followed the [Qonversion guide for Google Play Service Account](https://documentation.qonversion.io/docs/service-account-key-android) 
- linked correct project in Google Play Developer Console and provide valid credentials to Qonversion.

**Comment by jorgevalbuena56** [comment]
Hi @Maria-Bordunova 

I follow those steps and the only difference I found was in step #3, It says link an existing project but in my case that box was empty. Take a look at this screenshot

![image](https://user-images.githubusercontent.com/7516423/105486133-b9dfdc00-5cf9-11eb-82ca-a0aae4cc9d4d.png)

Tried searching using my project name and nothing popped up. So I decided to create a new project. Do you think that was a mistake?

<img width="1165" alt="Screen Shot 2021-01-22 at 9 42 57 pm" src="https://user-images.githubusercontent.com/7516423/105487213-72f2e600-5cfb-11eb-9c6f-4e8b4f105469.png">

I also double check the permissions of the qonversion account and they look correct

<img width="1191" alt="Screen Shot 2021-01-22 at 9 38 07 pm" src="https://user-images.githubusercontent.com/7516423/105486425-2c50bc00-5cfa-11eb-931f-912e8c252946.png">

**Comment by Maria-Bordunova** [comment]
@jorgevalbuena56 Yes, If you don't have a Google Cloud project yet, select Create new project and then Link existing project.
Screenshot from Qonversion documentation:
![doc](https://user-images.githubusercontent.com/39134139/105489173-e547d400-5cc3-11eb-9916-af12e22a4f3e.png)


I see the following message in your screenshot **There are no service account associated with this project.** 
Did you link the service account to Google Cloud Project after its creation?
![service account](https://user-images.githubusercontent.com/39134139/105489103-c2b5bb00-5cc3-11eb-8000-3dad2a069ca4.png)

**Comment by suriksarkisyan** [comment]
Hi @jorgevalbuena56 
How are you?
Is the problem fixed?

**Comment by jorgevalbuena56** [comment]
Hello, sorry for the very late response. Now is working, I am getting the permissions after I make the purchase. Now there's another issue. I am getting an active =0 and renewState = cancelled when in the play store the subscription is currently active. Check the attached screenshot

<img width="1398" alt="Screen Shot 2021-02-07 at 11 45 28 am" src="https://user-images.githubusercontent.com/7516423/107134074-7365c080-693a-11eb-988d-fd72fb1a9d39.png">

**Comment by suriksarkisyan** [comment]
Hi, @jorgevalbuena56 
That's how test purchases work.
The duration for the real subscription and for the test one is different.
Check details [here](https://developer.android.com/google/play/billing/test#renewals)

**Comment by jorgevalbuena56** [comment]
so when is the active variable equals 1? How can I make that variable =1 to trst my whole flow?

**Comment by suriksarkisyan** [comment]
Until the subscription expired. Denepds on the type, check the test subscription duration [here](https://developer.android.com/google/play/billing/test#renewals)
So just buy any subscription and check

**Comment by Maria-Bordunova** [comment]
@jorgevalbuena56 We can't see the whole scenario. In order to try to help you, let's try to test the entire flow from scratch, go through the documentation again, make sure that everything is set up correctly, clear the cache and app data, reinstall the app and try test again
