### ISSUE TITLE
yourSideUserID ?

### ISSUE THREAD

**Issue by Hamdaaa91** [qonversion/android-sdk#12]
I bit confused with the documentions 
is  "projectKey" the same as "Application Access Key" in setting tab
Also yourSideUserID --> whose used is it my app user ID or what

**Comment by smejl** [comment]
Hi, @Hamdaaa91 

Yep, projectKey is Application Access Key, You can find it [here].(https://qonversion.io/board/app/settings) 

"yourSideUserID" is user id in your system, that you use for third-party analytics, like Amplitude or Facebook. 

We send that property for matching clients. 

Thanks for pointing that out. We'll adjust the documentation.

**Comment by Hamdaaa91** [comment]
Thank you
