### ISSUE TITLE
Crash on Android 4.x when no Facebook app

### ISSUE THREAD

**Issue by alxgord** [qonversion/android-sdk#131]
- Qonversion SDK version: 2.7.3
- Android version: 4.x.x

Summary: application crashed on Qonverion SDK initialization when no Facebook app installed on device with Android version 4.x.x. There is not too much users affected by issue but it is present.

Stack trace: 
<img width="629" alt="Screenshot 2021-03-30 at 11 37 26" src="https://user-images.githubusercontent.com/17838017/112961417-03abcf00-914e-11eb-8d8d-4ef7e26ef3bc.png">
*Qonversion SDK version in report - 2.2.1

**Comment by Maria-Bordunova** [comment]
Hello, @alxgord !
Oh, it's disappointing. We'll reproduce the scenario and come back in the near future.

**Comment by Maria-Bordunova** [comment]
Hi again, @alxgord. We know how to fix the issue. But our new android sdk supports API level 16 or later. 
So could you specify the minSdkVersion of your app, please?  In case the minSdkVersion is 14 or 15, we are ready to prepare qonversion android-sdk release 2.2.2 for you.

**Comment by alxgord** [comment]
@Maria-Bordunova thank you for quick reaction on this issue! Currently in our project we have minSdkVersion 16. We will increase minSdkVersion to 21 in near future, so this bug is dont have big weight for us. Just for your information.

**Comment by Maria-Bordunova** [comment]
Hello, @alxgord .
New release 2.7.4 with fix is available :heavy_check_mark:
Thank you for your request and patience.

P.S. To install the new SDK version please use the following code:
     implementation '**io**.qonversion.android.sdk:sdk:2.+'
     
We've changed the installation way recently
