### ISSUE TITLE
Qoversion ANR

### ISSUE THREAD

**Issue by rlinoz** [qonversion/android-sdk#224]
Apparently Qonversion is being the source of a some of the ANRs our app is getting.

This is the log from Google Play:
![image](https://user-images.githubusercontent.com/5201282/134169191-5f71c11b-008e-4601-845c-ac2f22d1eafd.png)

And this are some of the devices and Android versions:
![image](https://user-images.githubusercontent.com/5201282/134169630-6f032f2c-6cee-4e1b-a76c-430f9056aa8b.png)
![image](https://user-images.githubusercontent.com/5201282/134169649-f7c98bad-d0d9-464b-bc57-ba51129fa2de.png)

Version of the SDK: 3.0.1

Our implementation is basically calling `Qonversion.launch` on our application `onCreate` using `observerMode` as `false`.

Should we be doing something different?

Meanwhile I am also updating to 3.1.2 to check if the issue is resolved.

**Comment by Maria-Bordunova** [comment]
Hi, @rlinoz. Thank you for the report!
We'll try to figure out what's going on.

**Comment by Maria-Bordunova** [comment]
@rlinoz Could you please share the full code block in the onCreate() method? You can send me an email `maria@qonversion.io`. 
When did you notice such errors? Maybe you catched these errors after you have added new calls to some methods at the app start?

**Comment by Maria-Bordunova** [comment]
Hi again @rlinoz.

Have you encountered the error one more time?

**Comment by rlinoz** [comment]
Hi @Maria-Bordunova ,

Since I started launching qonversion in another thread the problem never happened again.

**Comment by Maria-Bordunova** [comment]
Alright, thanks. I'll close the issue for now. 
If you have any questions, please don't hesitate to ask :raised_hands:.
