### ISSUE TITLE
Update to Google Billing Library 3.0 or 4.0?

### ISSUE THREAD

**Issue by rwrz** [qonversion/android-sdk#288]
Hello,

This SDK is still using Billing Library 2.0, right?
Can't we upgrade it to 3 or 4?

More than 1 year since the current version. This makes it impossible to use other SDKs together with this one.

Thanks

**Comment by suriksarkisyan** [comment]
Hi, @rwrz ✌️
Thanks for the question 😊
We support Google Billing Library 4 in our SDK's versions 3.+. 
And we also support Google Billing Library 3 in our SDK's 2.+ versions.
You can install our SDK as shown in our [documentation](https://documentation.qonversion.io/docs/android-sdk).
This way, you will get the SDK that supports Google Billing Library 4.

**Comment by rwrz** [comment]
Thank you @suriksarkisyan. You are right. My mistake.
Closing this.
