### ISSUE TITLE
Cannot create type for an unsupported classifier

### ISSUE THREAD

**Issue by TheRedSpy15** [qonversion/android-sdk#472]
Simply adding `implementation 'io.qonversion.android.sdk:sdk:4.4.0'` to my dependencies in the app build.gradle file, it causes a crash immediately whenever I try to get data from my backend (appwrite) like so:

```
try {
    val profileDoc = session?.let {
        database?.getDocument(
            databaseId = "641bd32164a107b4b80f",
            collectionId = "641fb3025db4c68463c2",
            documentId = it.userId,
        )
    }
    accountViewModel.onProfileChanged(Gson().fromJson(profileDoc?.data?.toJson(), Profile::class.java))
} catch (e: AppwriteException) {
    e.printStackTrace()
}
```

If I remove the `implementation 'io.qonversion.android.sdk:sdk:4.4.0'` from the build.gradle the issue goes away. I haven't even gotten to actually implementing the Qonversion code

Here's a more full version of the crash:

```
kotlin.reflect.jvm.internal.KotlinReflectionInternalError: Cannot create type for an unsupported classifier: T (class kotlin.jvm.internal.TypeParameterReference)
        at kotlin.reflect.full.KClassifiers.createType(KClassifiers.kt:45)
        at kotlin.reflect.jvm.internal.ReflectionFactoryImpl.typeOf(ReflectionFactoryImpl.java:123)
        at kotlin.jvm.internal.Reflection.typeOf(Reflection.java:123)
```

**Comment by TheRedSpy15** [comment]
Adding `implementation "org.jetbrains.kotlin:kotlin-reflect:1.7.10"` to my app build.gradle fixes it

This should be added to the setup instructions for kotlin users

**Comment by SpertsyanKM** [comment]
Hello! Thank you for your report!

As far as I can guess, the problem was caused by the difference between the `kotlin-reflect` library version used in our SDK and in the AppWrite SDK. Forcing the newer version (as you've done) solves it. But it's just an assumption. We want to investigate this problem and would appreciate it if you could answer the following questions: 

- What AppWrite SDK version do you use?
- Is `database?.getDocument()` the call causing the crash? If no, which line does it?

**Comment by TheRedSpy15** [comment]
> Hello! Thank you for your report!
> 
> As far as I can guess, the problem was caused by the difference between the `kotlin-reflect` library version used in our SDK and in the AppWrite SDK. Forcing the newer version (as you've done) solves it. But it's just an assumption. We want to investigate this problem and would appreciate it if you could answer the following questions:
> 
> * What AppWrite SDK version do you use?
> * Is `database?.getDocument()` the call causing the crash? If no, which line does it?

1. version 1.2.1
2. and yes it's the `database?.getDocument()` causing it

**Comment by SpertsyanKM** [comment]
Thank you for the information! We will try to reproduce the issue and will write back as soon as we have any news.

**Comment by SpertsyanKM** [comment]
I was able to reproduce the issue. The problem relates to the difference in Kotlin versions used in our and Appwrite's SDKs. As we use more elder version, I've created a task in our backlog to upgrade it in future releases. Thank you again for sharing this problem with us!
