### ISSUE TITLE
QonversionEntitlementsCallback returns an empty map

### ISSUE THREAD

**Issue by karimsinouh** [qonversion/android-sdk#567]
After successfully subscribing to a plan, the QonversionEntitlementsCallback callback returns an empty map. I can't know whether the subscription is active or not if the map is empty {}
I'm using version 7.2.0

**Comment by SpertsyanKM** [comment]
Hello, @karimsinouh. In order to help you we will need more information on your specific case including sensitive one. Could you please contact us using the support button on the bottom right of our [documentation](https://documentation.qonversion.io/docs/quickstart) page?

**Comment by karimsinouh** [comment]
@WiseKodama unfortunately I couldn't find a solution. Didn't get help from the support either, so I switched to another billing library

**Comment by WiseKodama** [comment]
> @WiseKodama unfortunately I couldn't find a solution. Didn't get help from the support either, so I switched to another billing library

That's what I was afraid of... I am not getting a response from support either or any of the devs on GitHub...
Thank you for letting me know.

**Comment by SpertsyanKM** [comment]
Hello! I'm sorry for the late reply. We are facing a high volume of support requests now, that's why it takes some time to reply. But I really want to help you! 

The problem from this issue depends on a variety of different things and to check all of them we might need some sensitive information from you, that is why we ask you to contact us via the support chat.

**Comment by WiseKodama** [comment]
> Hello! I'm sorry for the late reply. We are facing a high volume of support requests now, that's why it takes some time to reply. But I really want to help you!
> 
> The problem from this issue depends on a variety of different things and to check all of them we might need some sensitive information from you, that is why we ask you to contact us via the support chat.

I have provided code samples, Qonversion user IDs and exact issues. I have yet to receive a reply from support.

**Comment by SpertsyanKM** [comment]
@karimsinouh I'm sorry to hear that. If I can fix that situation, I would be happy to.

**Comment by SpertsyanKM** [comment]
@WiseKodama give me a while, I'll try to find your request

**Comment by SpertsyanKM** [comment]
Found [it](https://github.com/qonversion/unity-sdk/issues/243). Let's continue our conversation there.

**Comment by WiseKodama** [comment]
> Found [it](https://github.com/qonversion/unity-sdk/issues/243). Let's continue our conversation there.

That's the one, though we also have a Native Android app that is facing the issue, that is why I "reopened" this issue as well.

**Comment by SpertsyanKM** [comment]
Copying my reply here for historical purposes.

>  We had an issue on our side with handling Android consumable/non-consumable in-app purchases from the last two major versions of our SDKs (for Android SDK it's 7.0.0+). The bug has been relevant from the 9th of July till yesterday when we released the fix.

So if the problem occurs for consumable/non-consumable in-app purchases during the mentioned period, just try to reproduce it now - everything should work well.

**Comment by erizoo** [comment]
HI, I have same problem for android-sdk version 8.0.1
Can you help me?
What do you need information to help me?

**Comment by mihanovak1024** [comment]
@SpertsyanKM to lean on fellow colleague @WiseKodama's request, we're still experiencing the "empty entitlements map" issue after a successful (non-)consumable test in-app purchase (test Google Play card) on Android Qonversion SDK, both on 7.5.0 and 8.0.1.
Could you doublecheck that Qonversion BE changes from last week didn't get reverted?
