### ISSUE TITLE
Looking forward to contribute

### ISSUE THREAD

**Issue by herou** [qonversion/android-sdk#60]
Hello, 

My name is Eljo Prifti and I am a professional android developer with 4+ years of experience in Java/Kotlin working and living in Vienna, Austria. I came across this repo and I really like the product and I would like to contribute.

Do you welcome people who like to contribute?

**Comment by suriksarkisyan** [comment]
Hi, @herou 
Yeah, as we are an open source SDK you can contribute via fork + pull request.
You can open an issue about what do you want to contribute. After some discussion, if we can reach an agreement, you can start to work on some features for contribution.
Thank you for your interest in our project 😊😉

**Comment by herou** [comment]
@suriksarkisyan  Thank you.
