### ISSUE TITLE
Closed QonversionEntitlementsCallback returns an empty map

### ISSUE THREAD

**Issue by erizoo** [qonversion/android-sdk#618]
HI, I have same problem for android-sdk version 8.0.1
Can you help me?
What do you need information to help me?

**Comment by suriksarkisyan** [comment]
Hi, @erizoo 
Could you please describe the steps to reproduce the issue?
Send me the identifier of the user you faced the issue to s.sarkisyan@qonversion.io.

**Comment by mihanovak1024** [comment]
@SpertsyanKM same as @suriksarkisyan, we're also experiencing the "empty entitlements map" issue after a successful (non-)consumable test in-app purchase (test Google Play card) on Android Qonversion SDK, both on 7.5.0 and 8.0.1.
Could you doublecheck that Qonversion BE changes from last week (https://github.com/qonversion/android-sdk/issues/567) didn't get reverted?

Order number: GPA.3362-7681-1997-21357

**Comment by SpertsyanKM** [comment]
Hi, @mihanovak1024. Please give me a while, I'll check your purchase.

**Comment by SpertsyanKM** [comment]
Well, I see that there are no Google Play store credentials in your project settings, that's why we can't verify your purchases and provide entitlements. To fix it add them as described in [this documentation page](https://documentation.qonversion.io/docs/service-account-key-android).

**Comment by WiseKodama** [comment]
@SpertsyanKM We have recently transferred an app, which uses Qonversion.
Immediately following the transfer Qonversion started sending empty entitlements. 
The purchases are confirmed, but the list of entitlements are empty.

This is leading to a lot of frustration and us having to unpublish an application with 200k DAU.

The GCP was transferred along with the app and the service account user is added on Google Play Console. 
Is there anything else we might be missing?

**Comment by SpertsyanKM** [comment]
Hi @WiseKodama,

Have you updated the Android credentials in Qonversion Dashboard Settings after transferring the app?

**Comment by WiseKodama** [comment]
Which credentials specifically? 
The GCP was transfered with us, that is where the service account for Qonversion is. So the JSON stays the same, correct?
The Qonversion service account is added to the users in Play Console. 

Anything else we might be missing?

**Comment by SpertsyanKM** [comment]
Android Package Name should have been changed, have you updated it in our settings?

**Comment by SpertsyanKM** [comment]
Could you please explain then, what you mean by transferring the app?

**Comment by WiseKodama** [comment]
The app was at publisher A and we transferred it to us(publisher B) in it's entirety. 
App has been live for 10+ years and has more than 250m downloads. 

We transferred everything(reviews, users, etc.), the android package name does not change.

**Comment by SpertsyanKM** [comment]
Ah, got it, thank you. Could you please share the package name for your app, I'll try to check what's wrong with it now

**Comment by WiseKodama** [comment]
Sent to your linked github email.

**Comment by WiseKodama** [comment]
4.2.2 b240

**Comment by SpertsyanKM** [comment]
Were you receiving empty entitlements before on every test? I haven't changed anything regarding your project.

As I see, checking your purchases from our end were failing with the following error from Google: 

`The current user has insufficient permissions to perform the requested operation.`

It may be caused right because of transferring the app due to Google Play issue that can be easily fixed by editing any of your products as described [here](https://documentation.qonversion.io/docs/troubleshooting#missing-entitlements-after-purchase) at point 3.

Maybe you've edited any of your products and thus everything began working?

**Comment by WiseKodama** [comment]
We did not touch any IAP, but perhaps it took sometime to relink the
service account user?
Since that is not transferred with the app.

**Comment by SpertsyanKM** [comment]
It might be so, yes.

I see that the above error was happening in the following time intervals: 

5:41 - 15:22 UTC, 11/11
00:47 - 12:07 UTC, 12/11.

And there is no error for the last 40 minutes
