### ISSUE TITLE
Project does not compile

### ISSUE THREAD

**Issue by herou** [qonversion/android-sdk#63]
![image](https://user-images.githubusercontent.com/13895430/99960201-a31a1900-2d8c-11eb-829b-b2631bd0b609.png)

**Comment by herou** [comment]
@smejl I pulled master. May I need to pull another branch?

**Comment by smejl** [comment]
@herou please, use **main** branch.

**Comment by suriksarkisyan** [comment]
@herou use **main** branch, comment `signingConfigs` info as showed on screen and project will compile.
We will update info for contributors soon
![telegram-cloud-document-2-5323712993907706543](https://user-images.githubusercontent.com/16564309/100071942-ac6aba80-2e4c-11eb-929b-aa13319135a4.jpg)
