### ISSUE TITLE
when app's applicationId is diff from configured in Q for the project, as dev i would expect an error message

### ISSUE THREAD

**Issue by toreller** [qonversion/android-sdk#635]
I have got multiple build variants (product flavors) configured for my app, each have a unique applicationIdSuffix, and thus diff package name as applicationId. When I am running a variant other than configured in the Q project (applicationId), my app still connects to Q and can even download products (should be really able to?), but products arrive with storeDetails= null and skuDetails=null.

I would expect an error message when connecting to a Q project with a wrong applicationId.

**Comment by SpertsyanKM** [comment]
Hi @toreller,

Thank you for your report! The store details are missing because the Google Play Billing Library didn’t provide that information, as the application ID is different from the one configured.

While Qonversion does support cross-platform communication, we are still returning products without store details, especially since some could be iOS-only products.

I understand your expectation to receive an error for products that have a Google Play Product ID set but for which we couldn’t retrieve information from GPBL. What kind of error do you envision? It seems the only option might be to log that error to the console.

**Comment by toreller** [comment]
Ahoi @SpertsyanKM ,

   seems you misunderstood my request, let me be more specific. We configure the applicationId (package name) in Qonversion project settings like this:

![image](https://github.com/user-attachments/assets/36fe6d5e-1ca3-4952-b21a-6a7d702c6ea7)

In the app we initialize the Q client like this:
`        val qonversionConfig: QonversionConfig = QonversionConfig.Builder(
            this,
            "askldfghGHlhkGLKHghK_KLHGJH", // project key
            QLaunchMode.SubscriptionManagement
        )
            .setEnvironment(QEnvironment.Sandbox) // For Automation testing
            .build()
        Qonversion.initialize(qonversionConfig)
`
I would expect an exception thrown from Qonversion.initialize() when the app's actual applicationId is different from what configured in the Qonversion project settings. Or at least an error log saying something like "unable to initialize due to applicationId mismatch".

My assumption is that only apps with an applicationId matching the one configured in Q project settings should be able to access the billing data configured for that Q project.

**Comment by SpertsyanKM** [comment]
I appreciate the explanation! I’ll talk it over with the team and get back to you shortly. Thank you!

**Comment by SpertsyanKM** [comment]
Hi again, @toreller.

I’ve talked this over with the team, and we’ve decided not to implement the exception for a few key reasons. First, the application ID in the dashboard settings is crucial for validating purchases through the Google Play API, which ties into the issue of empty store details. A mismatch in package IDs might not necessarily cause empty store details, especially if the dashboard ID is incorrect. While it’s a valid concern, we don’t believe adding an exception in the code is the best way to address it. Additionally, we are logging warnings whenever the SDK fails to retrieve store details for any products listed in the dashboard.

We feel confident in this decision for now, but we’re definitely open to further discussion.

**Comment by toreller** [comment]
@SpertsyanKM,  I am most grateful for your attention to this matter.
